# Generated by Django 3.1.3 on 2020-12-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmationKey',
            fields=[
                ('id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('confirmation_key', models.CharField(blank=True, max_length=10, null=True)),
                ('key_generated_at', models.DateTimeField(blank=True, null=True)),
                ('key_valid_till', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
