# Generated by Django 3.1.3 on 2020-12-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0002_confirmationkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmationkey',
            old_name='id',
            new_name='key',
        ),
    ]
