# Generated by Django 3.1.3 on 2020-12-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0003_auto_20201228_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationkey',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confirmationkey',
            name='key',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
