# Generated by Django 3.1.3 on 2020-12-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0004_auto_20201228_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationkey',
            name='initial_request_sent',
            field=models.BooleanField(default=False),
        ),
    ]
