# Generated by Django 3.1.3 on 2020-12-30 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Config', '0005_confirmationkey_initial_request_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationkey',
            name='key_valid_till',
        ),
        migrations.CreateModel(
            name='PasswordResetKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=20, null=True)),
                ('key_generated_at', models.DateTimeField(blank=True, null=True)),
                ('initial_request_sent', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
