# Generated by Django 3.1.3 on 2020-12-30 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0006_auto_20201229_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetkey',
            name='initial_request_sent',
        ),
    ]
