# Generated by Django 3.1.3 on 2020-12-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0008_auto_20201230_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
