# Generated by Django 3.1.3 on 2021-01-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0009_auto_20201230_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='Data/Users/Profiles'),
        ),
    ]
