# Generated by Django 3.1.3 on 2021-01-05 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Config', '0011_auto_20210105_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followRequests',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followRequestsSend',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followRequests', models.ManyToManyField(blank=True, related_name='follow_requests_got', to='Config.Profile')),
                ('following', models.ManyToManyField(blank=True, related_name='i_follow', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Config.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followRequestsSent', models.ManyToManyField(blank=True, related_name='follow_requests_sent', to='Config.Profile')),
                ('followers', models.ManyToManyField(blank=True, related_name='my_followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Config.profile')),
            ],
        ),
    ]
