# Generated by Django 3.1.3 on 2021-01-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0012_auto_20210105_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='followRequestsSent',
            new_name='followRequests',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='followRequests',
            new_name='followRequestsSent',
        ),
    ]
